### ISSUE TITLE
maintainer(s) wanted?

### ISSUE THREAD

**Issue by flrgh** [LuaCATS/openresty#1]
Hi @carsakiller :wave:

I'm not sure what kind of governance model we're looking at with this new org, but if you're looking for volunteers, I am happy to help out with maintenance of this repository.

Qualifications:
* I have been contributing to lua-language-server typedefs [since 2021](https://github.com/LuaLS/lua-language-server/commits?author=flrgh)
* I have 5+ years of experience with the framework and continue to [write OpenResty-related code every day](https://github.com/Kong/kong/commits?author=flrgh)

**Comment by flrgh** [comment]
@CppCXY may be interested as well; I _think_ they contributed the initial version of the OpenResty typedefs.

**Comment by carsakiller** [comment]
Hey @flrgh!

That would be great to have your help! I have personally never used OpenResty, in fact, I have pretty much only used Lua exclusively in games (with all the limitations that they bring). I can still see you make some very detailed definitions, though!

I am still thinking about how LuaCATS should operate. There is a lot to consider and manage, and we are just getting started 😛. I want it to be easy for people to collaborate on and contribute to, but there are obviously also risks with things being too open—not limited to [malicious scripts making their way onto people's computers](https://github.com/LuaLS/vscode-lua/issues/112) and organizational hell. I do think having some core maintainers is what will make this possible, so I'll send you an invitation to maintain OpenResty. Let me know if there are any other projects you are able to help out on. At some point soon, I want to draft up a `CONTRIBUTING.md` template as well to be used across all the LuaCATS repos, at least as a default.

As for @CppCXY, let me know if you are interested as well!

**Comment by CppCXY** [comment]
I'm glad you mentioned me, but I'm not an OpenResty developer, I make the initial version of the OpenResty typedefs just for emmylua, and then invited by sumneko to add some API documentation for his project.
I may not be able to participate in the maintenance of community documentation.
but it's still nice if you invite me

**Comment by carsakiller** [comment]
@CppCXY I've added you as well

**Comment by CppCXY** [comment]
thank you, I have accepted it
